services:
  backend:
    build: .
    ports:
      - ${BACKEND__RUN__PORT}:${BACKEND__RUN__PORT}
    depends_on:
      postgres-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND__RUN__PORT}/api/ping || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 5
    env_file:
      - .env

  postgres-backend:
    image: postgres:16-alpine
    ports:
      - ${BACKEND__DB__PORT}:${BACKEND__DB__PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${BACKEND__DB__USER}
      - POSTGRES_PASSWORD=${BACKEND__DB__PASSWORD}
      - POSTGRES_DB=${BACKEND__DB__NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: -p ${BACKEND__DB__PORT}
